// What this file does: Express router for all Twilio call-related endpoints.
//
// Routes:
//   POST /api/call/make-call  → makeCall     (called by our React frontend — no Twilio validation)
//   POST /api/call/voice      → voiceWebhook (Twilio webhook — request validated)
//   POST /api/call/process    → processInput (Twilio Gather callback — request validated)
//   POST /api/call/status     → callStatus   (Twilio statusCallback — request validated)
//   GET  /api/call/tts-audio/:filename → serves temp TTS mp3 files for twiml.play()

const express       = require('express');
const path          = require('path');
const fs            = require('fs');
const twilioValidate = require('../middleware/twilioValidate');
const {
  makeCall,
  voiceWebhook,
  processInput,
  callStatus,
} = require('../controllers/callController');

const router = express.Router();

// ── Frontend-initiated call request (no Twilio validation needed) ───────────
router.post('/make-call', makeCall);

// ── Twilio webhooks (all protected by signature validation) ─────────────────
router.post('/voice',   twilioValidate, voiceWebhook);
router.post('/process', twilioValidate, processInput);
router.post('/status',  twilioValidate, callStatus);

// ── Serve temporary TTS audio files generated by voiceWebhook ───────────────
// Files are written to backend/temp_uploads/ and auto-deleted after 60 seconds.
router.get('/tts-audio/:filename', (req, res) => {
  const filename = path.basename(req.params.filename); // prevent path traversal
  const filePath = path.join(__dirname, '..', 'temp_uploads', filename);

  if (!fs.existsSync(filePath)) {
    return res.status(404).send('Audio file not found or already expired.');
  }

  res.type('audio/mpeg');
  fs.createReadStream(filePath).pipe(res);
});

module.exports = router;
